# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: brentian.io
email: brentian@github.com
description: >- # this means to ignore newlines until "baseurl:"
  brentian.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: brentian

future: true

# TODO(jez): figure out how to get optional TOC? we'd need to:
#   - update the 'extensions:' below
#   - grab it from the generated pandoc
#   - add it to the default.html template
markdown: kramdown
# pandoc:
#   extensions:
#     - section-divs
#     - from: 'markdown+tex_math_dollars'
#     - filter: 'pandoc-sidenote'
#     - filter: 'pandoc-citeproc'
#     - csl: assets/or.csl
#     - bibliography: assets/bib/aps.ref.bib

# HACK(jez): We have to hard code the site.baseurl here
header_includes:
  - '<link rel="apple-touch-icon-precomposed" href="/assets/img/touch-icon.png">'
  - '<link rel="icon" sizes="32x32" href="/assets/img/favicon@2x.png">'
  - '<link rel="icon" sizes="16x16" href="/assets/img/favicon.png">'
  - '<link rel="stylesheet" href="/assets/css/extras.css">'

plugins:
  - jekyll-feed
  # - jekyll-pandoc
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - tags
  - drafts
  - notes

# Octopress configuration

post_ext: md
page_ext: md

# Default templates for posts and pages
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: post
